name: Inventing the wheel 😅
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12'] # Specify Python versions 3.10 and above
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install maturin
        run: pip install maturin
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Add any other dependencies your package may require
          pip install maturin
      - name: Build package with maturin
        run: maturin develop --release
      - name: Run tests (optional)
        run: |
          python -c "import your_package; your_package.test()"  # Replace with actual test command
      - name: Upload artifacts (optional)
        uses: actions/upload-artifact@v4
        with:
          name: built-wheel
          path: target/wheels/* # Path to the wheels
